network:
  renderer: networkd
  version: 2
  ethernets:
    eth0:
      dhcp4: true
  wifis:
    wlan0:
      dhcp4: false
      addresses: [10.9.9.1/24]
      access-points:
        "dumbap":
          password: ""