<?php

require '../../includes/csrf.php';

require_once '../../includes/config.php';
require_once '../../includes/functions.php';

if (isset($_POST['interface'])) {
    $jsonFile = RASPI_CONFIG_NETWORKING . CONFIG_NETWORK_FILENAME . ".json";
    // Check if file exists: if not, call python scritp to generate it.
    if (!file_exists($jsonFile)) {
        // This script will convert netplan's yaml configuration file to json so it's php friendly.
        exec("python3 " . YAML_SCRIPT . " yaml_to_json " . NETPLAN_CONFIG_FILE);
    }
    // Read json file generated by script and located in RASPI_CONFIG_NETWORKING
    $data = file_get_contents($jsonFile);
    $jsonData = json_decode($data, true);
    $jsonData = ['return'=>1,'output'=>['intConfig'=>$data]];
    echo json_encode($jsonData);
}
else {
    $jsonData = ['return'=>2,'output'=>['Error getting data']];
    echo json_encode($jsonData);
}
